# Generated by Django 2.0.3 on 2018-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
