# Generated by Django 2.0.3 on 2018-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='pizza_name',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='text',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
