# Generated by Django 2.0.3 on 2018-03-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'pizza_stuff'},
        ),
    ]
