# Generated by Django 2.0.3 on 2018-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_topping_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'pizza'},
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.TextField(),
        ),
    ]
